name: "Greeting Action"
description: "Sends a greeting message"
inputs:
  name:
    description: "Name of the person to greet"
    required: true
    default: "World"
runs:
  using: "node16"
  main: "index.js"
